### PR TITLE
Fix the BAG3 primitives setup to match technology design parameters

### PR DESCRIPTION
**Pull request by zhaokai-l**
Fix the BAG3 primitives setup to match the technology design parameters.
 * Updated BAG routing grid
 * Updated metal width/space and via specs in `tech_params.yaml`
 * Changed transistor gate and implant implementation in primitives

### CODE REVIEW

**Comment by zhaokai-l** [comment]
@googlebot I signed it!

**Comment by zhaokai-l** [comment]
@googlebot I signed it!

**Comment by mithro** [comment]
@zhaokai-l - Can you update the pull request description with some details about what these changes do and why they are needed? If you do that I can then merge this.

**Comment by zhaokai-l** [comment]
1. Update BAG routing grid
2. Update metal width/space and via specs in tech_params.yaml
3. Change transistor gate and implant implementation in primitives

**Comment by mithro** [comment]
Thanks for the explanation of what change but you didn't explain why those changes are needed?

**Comment by zhaokai-l** [comment]
I think the primitives we got first is not completed. So I updated the primitives implementation to draw a correct transistor. And for the routing grid and metal/via specs, it seems to me the first version is a copy from other generic technology like cds_ff_mpt or just some default values. So we need to update specs in tech_params.yaml to match the design rules.

**Comment by mithro** [comment]
@zhaokai-l -- See the updated description at the top of the pull request, does that look good?

**Comment by zhaokai-l** [comment]
Thanks for adding that! It looks good. I'll make sure adding some detail descriptions in the future.

**Comment by mithro** [comment]
Merged!

**Pull request merged**
